project:
  type: website
  output-dir: docs

website:
  title: "Alexander Meehan"
  favicon: images/favicon.ico
  navbar:
    title: false
    logo: images/favicon.ico
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: projects/index.qmd
        text: Projects
      - href: Python.qmd
        text: Python
      - href: reflection.qmd
        text: Reflections
    right:
      - href: contact.qmd
        text: Contact
      - href: https://github.com/alexandermeehan
        text: GitHub
        target: _blank

footer:
    left: "© 2026 Alexander Meehan"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      light:
        - flatly
        - styles.scss
        - styles-light.scss
      dark:
        - darkly
        - styles.scss