project:
  type: website
  output-dir: docs

website:
  title: "Alexander Meehan"
  favicon: images/favicon.ico
  navbar:
    logo: images/favicon.ico
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Projects
        menu:
          - href: projects/index.qmd
            text: All Projects
      - href: Python.qmd
        text: Python
      - href: reflection.qmd
        text: Reflections
    right:
      - href: contact.qmd
        text: Contact
      - href: cv.qmd
        text: CV
        target: _blank
      - icon: github
        href: https://github.com/alexandermeehan
        target: _blank
  page-footer:
    left: "Copyright 2026 Alexander Meehan"
    right:
      - icon: github
        href: https://github.com/alexandermeehan
      - icon: linkedin
        href: https://linkedin.com/in/alexander-meehan-267875208
      - icon: envelope
        href: mailto:alex.meehan2001@gmail.com
    center: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      light:
        - flatly
        - styles.scss
        - styles-light.scss
      dark:
        - darkly
        - styles.scss